after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 40

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]

# Focus

alt-ctrl-shift-a = 'focus left'
alt-ctrl-shift-s = 'focus down'
alt-ctrl-shift-d = 'focus up'
alt-ctrl-shift-f = 'focus right'

alt-ctrl-shift-t = 'focus-monitor --wrap-around next'
alt-ctrl-shift-g = 'workspace --wrap-around next'
alt-ctrl-shift-b = ['move-workspace-to-monitor --wrap-around next', 'mode main']
alt-ctrl-shift-w = ['move-node-to-workspace --wrap-around next','workspace --wrap-around next', 'mode main']

alt-ctrl-shift-j = 'workspace J'
alt-ctrl-shift-k = 'workspace K'
alt-ctrl-shift-l = 'workspace L'
alt-ctrl-shift-u = 'workspace U'
alt-ctrl-shift-i = 'workspace I'
alt-ctrl-shift-o = 'workspace O'

# Toggle window style

alt-ctrl-shift-m = ['layout tiles horizontal vertical', 'mode main']
alt-ctrl-shift-comma = ['layout accordion horizontal vertical', 'mode main']
alt-ctrl-shift-period = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

# Move / resize

alt-ctrl-shift-z = 'move left'
alt-ctrl-shift-x = 'move down'
alt-ctrl-shift-c = 'move up'
alt-ctrl-shift-v = 'move right'

alt-ctrl-shift-e = 'resize smart -50'
alt-ctrl-shift-r = 'resize smart +50'

# Modes

alt-ctrl-shift-q = 'mode advanced'

# --- Mode Advanced Management
[mode.advanced.binding]

g = ['move-node-to-monitor --wrap-around next', 'mode main']

j = ['move-node-to-workspace J','workspace J', 'mode main']
k = ['move-node-to-workspace K','workspace K', 'mode main']
l = ['move-node-to-workspace L','workspace L', 'mode main']
u = ['move-node-to-workspace U','workspace U', 'mode main']
i = ['move-node-to-workspace I','workspace I', 'mode main']
o = ['move-node-to-workspace O','workspace O', 'mode main']

a = ['join-with left', 'mode main']
d = ['join-with up', 'mode main']
s = ['join-with down', 'mode main']
f = ['join-with right', 'mode main']

q = ['reload-config', 'mode main']
w = ['flatten-workspace-tree', 'mode main'] # reset layout

# backspace = ['close-all-windows-but-current', 'mode main']

# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
# Assigned workspaces cannot be moved, so use O and L for workspaces to you want to move between monitors
[workspace-to-monitor-force-assignment]
U = '^built-in retina display$'
I = '^built-in retina display$'
J = ['^LG UltraFine$', '^dell$', 'main']
K = ['^LG UltraFine$', '^dell$', 'main']

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace J'

# [[on-window-detected]]
# if.app-id = 'company.thebrowser.Browser'
# run = 'move-node-to-workspace K'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace U'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace U'
