after-login-command = []
after-startup-command = []
start-at-login = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 40

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]

# Focus
alt-ctrl-shift-a = 'focus --boundaries-action wrap-around-the-workspace dfs-prev'
alt-ctrl-shift-f = 'focus --boundaries-action wrap-around-the-workspace dfs-next'
alt-ctrl-shift-d = 'workspace --wrap-around next'
alt-ctrl-shift-s = 'focus-monitor --wrap-around next'

alt-ctrl-shift-z = 'workspace 4'
alt-ctrl-shift-x = 'workspace 3'
alt-ctrl-shift-c = 'workspace 2'
alt-ctrl-shift-v = 'workspace 1'


# Change structure

alt-ctrl-shift-r = 'layout h_tiles h_accordion' # Toggle layouts horizontal
alt-ctrl-shift-e = 'layout v_tiles v_accordion' # Toggle layouts vertical
alt-ctrl-shift-u = 'resize smart -50'
alt-ctrl-shift-o = 'resize smart +50'

# Move

alt-ctrl-shift-m = 'move-workspace-to-monitor --wrap-around next'
alt-ctrl-shift-comma = 'move-node-to-workspace --focus-follows-window --wrap-around next'
alt-ctrl-shift-period = 'move-node-to-monitor --focus-follows-window --wrap-around next'

alt-ctrl-shift-j = 'move left'
alt-ctrl-shift-k = 'move down'
alt-ctrl-shift-i = 'move up'
alt-ctrl-shift-l = 'move right'
