after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 40

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]

# Focus

alt-ctrl-shift-a = 'focus left'
alt-ctrl-shift-s = 'focus up'
alt-ctrl-shift-d = 'focus down'
alt-ctrl-shift-f = 'focus right'

alt-ctrl-shift-z = 'workspace 1'
alt-ctrl-shift-x = 'workspace 2'
alt-ctrl-shift-c = 'workspace 3'
alt-ctrl-shift-v = 'workspace 4'

alt-ctrl-shift-b = 'workspace --wrap-around next'
alt-ctrl-shift-g = 'focus-monitor --wrap-around next'

# Change structure

alt-ctrl-shift-t = 'layout h_tiles h_accordion' # Toggle horizontal layouts
alt-ctrl-shift-e = 'resize smart -50'
alt-ctrl-shift-r = 'resize smart +50'

# Move

alt-ctrl-shift-m = 'move-workspace-to-monitor --wrap-around next'
alt-ctrl-shift-comma = ['move-node-to-workspace --wrap-around next','workspace --wrap-around next']
alt-ctrl-shift-period = ['move-node-to-monitor --wrap-around next','focus-monitor --wrap-around next']

alt-ctrl-shift-j = 'move left'
alt-ctrl-shift-k = 'move down'
alt-ctrl-shift-l = 'move up'
alt-ctrl-shift-p = 'move right'

alt-ctrl-shift-o = 'reload-config'
alt-ctrl-shift-i = 'flatten-workspace-tree'