# Directory Watcher Configuration
# This file defines automated file movement rules for different computers
# Each watcher monitors a source directory and moves new files to a target directory

watchers:
  # Example configuration - customize for your specific needs
  - source: "~/misc/downloads"
    target: "~/misc/movies"
    computer: "MacBook-Pro"
    enabled: true
    description: "Auto-move downloads to movies folder"
  
  - source: "~/Desktop/screenshots"
    target: "~/Pictures/Screenshots"
    computer: "MacBook-Pro"
    enabled: false
    description: "Organize desktop screenshots"

# Configuration format:
# - source: "string"      # Required: Source directory path (supports ~ expansion)
# - target: "string"      # Required: Target directory path (supports ~ expansion)  
# - computer: "string"    # Required: Computer identifier (use MenuHammer to get yours)
# - enabled: boolean      # Optional: Defaults to true
# - description: "string" # Optional: Human-readable description

# To find your computer identifier:
# Use F19 → Scripts → "Copy Computer Name" in MenuHammer